=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/lwpm-json-schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "scripts": {
      "type": "object",
      "properties": {
        "test": {
          "type": "string"
        }
      }
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/7zip/lwpm.json
{
  "name": "7zip",
  "description": "7-Zip is a file archiver with a high compression ratio",
  "version": "1900",
  "pre-version": "1900",
  "homepage": "https://www.7-zip.org/",
  "bug": "https://www.7-zip.org/support.html",
  "github": "",
  "releases": "https://www.7-zip.org/download.html",
  "url": "https://www.7-zip.org/a/7z${VERSION}-x64.msi"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/edge/lwpm.json
{
  "name": "edge",
  "description": "",
  "version": "",
  "pre-version": "",
  "homepage": "https://www.microsoftedgeinsider.com",
  "bug": "",
  "github": "",
  "releases": "https://www.microsoftedgeinsider.com/en-us/download/",
  "url": "",
  "url-mirror": "",
  "pre-url": "",
  "pre-url-mirror": "",
  "scripts": {
    "preinstall": "",
    "install": "",
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "",
    "postuninstall": "",
    "pretest": "",
    "test": "",
    "posttest":""
  },
  "path": [

  ]
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/coredns/lwpm.json
{
  "name": "coredns",
  "description": "CoreDNS is a DNS server that chains plugins",
  "version": "1.6.7",
  "pre-version": "1.6.7",
  "homepage": "https://coredns.io/",
  "bug": "https://github.com/coredns/coredns/issues",
  "github": "coredns/coredns",
  "releases": "https://github.com/coredns/coredns/releases",
  "url": "https://github.com/coredns/coredns/releases/download/v${VERSION}/coredns_${VERSION}_windows_amd64.tgz"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/zeal/lwpm.json
{
  "name": "zeal",
  "description": "Offline documentation browser inspired by Dash",
  "version": "0.6.1",
  "pre-version": "0.6.1",
  "homepage": "https://zealdocs.org/",
  "bug": "https://github.com/zealdocs/zeal/issues",
  "github": "zealdocs/zeal",
  "releases": "https://github.com/zealdocs/zeal/releases"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/yarn/lwpm.json
{
  "name": "yarn",
  "description": "Fast, reliable, and secure dependency management",
  "version": "1.22.0",
  "pre-version": "1.22.0",
  "homepage": "https://www.yarnpkg.com/lang/en/",
  "bug": "https://github.com/yarnpkg/yarn/issues",
  "github": "yarnpkg/yarn",
  "releases": "https://github.com/yarnpkg/yarn/releases",
  "url": "https://github.com/yarnpkg/yarn/releases/download/v${VERSION}/yarn-${VERSION}.msi",
  "url-mirror": "https://mirrors.huaweicloud.com/yarn/v${VERSION}/yarn-${VERSION}.msi"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/etcd/lwpm.json
{
  "name": "etcd",
  "description": "Distributed reliable key-value store for the most critical data of a distributed system",
  "version": "3.4.7",
  "pre-version": "3.4.7",
  "homepage": "https://etcd.io/",
  "bug": "https://github.com/etcd-io/etcd/issues",
  "github": "etcd-io/etcd",
  "releases": "https://github.com/etcd-io/etcd/releases",
  "url": "https://github.com/etcd-io/etcd/releases/download/v${VERSION}/etcd-v${VERSION}-windows-amd64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/etcd/v${VERSION}/etcd-v${VERSION}-windows-amd64.zip"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/github-release/lwpm.json
{
  "name": "github-release",
  "description": "Commandline app to create and edit releases on Github (and upload artifacts)",
  "version": "0.7.2",
  "pre-version": "0.7.2",
  "homepage": "https://github.com/aktau/github-release",
  "bug": "https://github.com/aktau/github-release/issues",
  "github": "aktau/github-release",
  "releases": "https://github.com/aktau/github-release/releases"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/vclib/lwpm.json
{
  "name": "vclib",
  "description": "Microsoft Visual C++ Redistributable for Visual Studio 2019",
  "version": "16.0.0",
  "pre-version": "16.0.0",
  "homepage": "https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads",
  "bug": "",
  "github": "",
  "releases": "",
  "url": "https://aka.ms/vs/16/release/VC_redist.x64.exe"
}
