=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/lwpm-json-schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "scripts": {
      "type": "object",
      "properties": {
        "test": {
          "type": "string"
        }
      }
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/go/lwpm.json
{
  "name": "go",
  "description": "Go is an open source programming language that makes it easy to build simple, reliable, and efficient software",
  "version": "1.14.2",
  "pre-version": "1.14.2",
  "homepage": "https://golang.google.cn/",
  "bug": "https://github.com/golang/go/issues",
  "github": "golang/go",
  "releases": "https://github.com/golang/go/releases",
  "url": "https://dl.google.com/go/go${VERSION}.windows-amd64.zip"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/docker/lwpm.json
{
  "name": "docker",
  "description": "Docker: the open-source application container engine",
  "version": "stable",
  "pre-version": "edge",
  "homepage": "https://www.docker.com/",
  "bug": "https://github.com/docker/for-win/issues",
  "github": "docker/docker-ce",
  "releases": "https://github.com/docker/docker-ce/releases",
  "url": "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe",
  "pre-url": "https://download.docker.com/win/edge/Docker%20Desktop%20Installer.exe"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/nginx/lwpm.json
{
  "name": "nginx",
  "description": "small, powerful, scalable web/proxy server",
  "version": "1.18.0",
  "pre-version": "1.17.10",
  "homepage": "https://nginx.org",
  "bug": "http://nginx.org/en/support.html",
  "github": "nginx/nginx",
  "releases": "https://nginx.org/en/download.html",
  "url-mirror": "https://mirrors.huaweicloud.com/nginx/nginx-${VERSION}.zip",
  "url": "https://nginx.org/download/nginx-${VERSION}.zip"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/python/lwpm.json
{
  "name": "python",
  "description": "Python is a programming language that lets you work quickly and integrate systems more effectively",
  "version": "3.8.2",
  "pre-version": "3.8.2",
  "homepage": "https://www.python.org/",
  "bug": "",
  "github": "python/cpython",
  "releases": "https://www.python.org/downloads/",
  "url": "https://www.python.org/ftp/python/${VERSION}/python-${VERSION}-amd64.exe",
  "url-mirror": "https://mirrors.huaweicloud.com/python/${VERSION}/python-${VERSION}-amd64.exe",
  "pre-url": "https://www.python.org/ftp/python/${VERSION}/python-${VERSION}-amd64.exe",
  "pre-url-mirror": "https://mirrors.huaweicloud.com/python/${VERSION}/python-${VERSION}-amd64.exe"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/vim/lwpm.json
{
  "name": "vim",
  "description": "Vi IMproved - enhanced vi editor",
  "version": "8.2.0539",
  "pre-version": "8.2.0539",
  "homepage": "https://www.vim.org/",
  "bug": "https://github.com/vim/vim-win32-installer/issues",
  "github": "vim/vim-win32-installer",
  "releases": "https://github.com/vim/vim-win32-installer/releases"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/git/lwpm.json
{
  "name": "git",
  "description": "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency",
  "version": "2.26.0",
  "pre-version": "2.26.0",
  "homepage": "https://git-scm.com/",
  "bug": "https://git-scm.com/community",
  "github": "git/git",
  "releases": "https://github.com/git/git/releases",
  "pre-url" : "",
  "url": "https://github.com/git-for-windows/git/releases/download/v${VERSION}.windows.1/Git-${VERSION}-64-bit.exe",
  "url-mirror":"https://mirrors.huaweicloud.com/git-for-windows/v${VERSION}.windows.1/Git-${VERSION}-64-bit.exe"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/helm/lwpm.json
{
  "name": "helm",
  "description": "The Kubernetes Package Manager",
  "version": "3.2.0",
  "pre-version": "3.2.0",
  "homepage": "https://helm.sh/",
  "bug": "https://github.com/helm/helm/issues",
  "github": "helm/helm",
  "releases": "https://github.com/helm/helm/releases",
  "url": "https://get.helm.sh/helm-v${VERSION}-windows-amd64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/helm/v${VERSION}/helm-v${VERSION}-windows-amd64.zip"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/node/lwpm.json
{
  "name": "node",
  "description": "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine",
  "version": "12.16.2",
  "pre-version": "14.0.0",
  "homepage": "https://nodejs.org/en/",
  "bug": "https://github.com/nodejs/node/issues",
  "github": "nodejs/node",
  "releases": "https://nodejs.org/en/download/",
  "url": "https://nodejs.org/dist/v${VERSION}/node-v${VERSION}-win-x64.zip",
  "url-mirror": "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v${VERSION}/node-v${VERSION}-win-x64.zip"
}
