=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/lwpm-json-schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "scripts": {
      "type": "object",
      "properties": {
        "test": {
          "type": "string"
        }
      }
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/composer/lwpm.json
{
  "name": "composer",
  "description": "Dependency Manager for PHP",
  "version": "1.10.5",
  "pre-version": "1.10.5",
  "homepage": "https://getcomposer.org/",
  "bug": "https://github.com/composer/composer/issues",
  "github": "composer/composer",
  "releases": "https://getcomposer.org/download/"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/minio/lwpm.json
{
  "name": "minio",
  "description": "MinIO is a high performance object storage server compatible with Amazon S3 APIs",
  "version": "RELEASE.2020-03-25T07-03-04Z",
  "pre-version": "RELEASE.2020-03-25T07-03-04Z",
  "homepage": "https://min.io/",
  "bug": "https://github.com/minio/minio/issues",
  "github": "minio/minio",
  "releases": "https://github.com/minio/minio/releases"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/gpg/lwpm.json
{
  "name": "gpg",
  "description": "",
  "version": "3.1.11",
  "pre-version": "3.1.11",
  "homepage": "https://gnupg.org/",
  "bug": "",
  "github": "gpg/gpg4win",
  "releases": "",
  "url": "https://files.gpg4win.org/gpg4win-${VERSION}.exe",
  "url-mirror": "",
  "pre-url": "",
  "pre-url-mirror": "",
  "scripts": {
    "preinstall": "",
    "install": "",
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "",
    "postuninstall": "",
    "pretest": "",
    "test": "gpg --version",
    "posttest":""
  },
  "path": [
    "C:\\Program Files (x86)\\GnuPG\\bin"
  ]
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/dive/lwpm.json
{
  "name": "dive",
  "description": "A tool for exploring each layer in a docker image",
  "version": "0.9.2",
  "pre-version": "0.9.2",
  "homepage": "https://github.com/wagoodman/dive",
  "bug": "https://github.com/wagoodman/dive/issues",
  "github": "wagoodman/dive",
  "releases": "https://github.com/wagoodman/dive/releases"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/mpv/lwpm.json
{
  "name": "mpv",
  "description": "Video player based on MPlayer/mplayer2",
  "version": "0.32.0",
  "pre-version": "20200412-git-530a086",
  "homepage": "https://mpv.io/",
  "bug": "https://mpv.io/bug-reports/",
  "github": "mpv-player/mpv",
  "releases": "https://github.com/mpv-player/mpv/releases",
  "url": "https://astuteinternet.dl.sourceforge.net/project/mpv-player-windows/stable/mpv-${VERSION}-x86_64.7z",
  "pre-url": "https://astuteinternet.dl.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-${VERSION}.7z",
  "path": [
    "%ProgramData%\\mpv"
  ]
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/lwpm.json
{
  "name": "example",
  "description": "",
  "version": "x.y.z",
  "pre-version": "x.y.z-alpha.1",
  "homepage": "",
  "bug": "",
  "github": "repo/name",
  "releases": "",
  "url": "",
  "url-mirror": "",
  "pre-url": "",
  "pre-url-mirror": "",
  "scripts": {
    "preinstall": "",
    "install": "",
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "",
    "postuninstall": "",
    "pretest": "",
    "test": "",
    "posttest":"",
    "version": ""
  },
  "path": [
    "C:/bin"
  ]
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/frp/lwpm.json
{
  "name": "frp",
  "description": "A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet",
  "version": "0.32.1",
  "pre-version": "0.32.1",
  "homepage": "https://github.com/fatedier/frp",
  "bug": "https://github.com/fatedier/frp/issues",
  "github": "fatedier/frp",
  "releases": "https://github.com/fatedier/frp/releases",
  "url": "https://github.com/fatedier/frp/releases/download/v${VERSION}/frp_${VERSION}_windows_amd64.zip"
}

=== github-clonner/lnmp/windows/lnmp-windows-pm-repo/chrome/lwpm.json
{
  "name": "chrome",
  "description": "",
  "version": "",
  "pre-version": "",
  "homepage": "https://www.google.cn/chrome/index.html",
  "bug": "",
  "github": "",
  "releases": "https://www.google.cn/intl/zh-CN/chrome/canary/",
  "url": "",
  "url-mirror": "",
  "pre-url": "",
  "pre-url-mirror": "",
  "scripts": {
    "preinstall": "",
    "install": "",
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "",
    "postuninstall": "",
    "pretest": "",
    "test": "",
    "posttest":""
  },
  "path": [
    "C:/bin"
  ]
}
